<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="styless8.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?famiy=Press+Start+2P&display=swap"
      rel="stylesheet"
    />
  </head>

  <body class="main">
    <div class="box">
      <div class="box__column box__column--nav">
        <nav>
          <ul class="box__list">
            <li>
              <a href="#"><img src="https://image.flaticon.com/icons/png/512/117/117107.png" /></a>
            </li>
            <li>
              <a href="#"><img src="https://image.flaticon.com/icons/png/512/107/107794.png" /></a>
            </li>
            <li>
              <a href="#"><img src="https://image.flaticon.com/icons/png/512/39/39751.png" /></a>
            </li>
            <li>
              <a href="#"><img src="https://image.flaticon.com/icons/png/512/93/93789.png" /></a>
            </li>
            <li>
              <a href="#"><img src="https://image.flaticon.com/icons/png/512/95/95333.png" /></a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="box__column box__column--content">
        <h1 class="box__title">Arkadiusz Wiewiórka</h1>
        <p class="box__paragraph">Front-end Developer</p>
        <div class="box__button">
          <a
            href="file:///C:/Users/AREK/Desktop/programowanie%204/pr%C3%B3ba.html"
            ><button class="box__btn">CONTACT</button></a
          >
        </div>
        <pre class="box__info">
              {
                <span class="box__span">Autor:</span><span>Arkadiusz Wiewiórka</span>
                <span class="box__span">Data urodzenia:</span><span>07.05.1981</span>
                
                <span class="box__span">Umiejętności</span>:
                  
                  HTML
                  CSS
                  REACT
                  SASS
                  NETLIFY

                  <span class="box__span">Języki:</span>

                  Angielski
                }  
                
              </pre>
      </div>
    </div>
  </body>
</html>
